apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: bakehouse-http
  labels:
    app: bakehouse
spec:
  type: NodePort
  selector:
    app: bakehouse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30021